#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

mount_encfs() {
  NAME=$(basename $1)
  encfs $1 /Volumes/$NAME -o volname=$NAME -o local -o allow_root
  sleep 2
  sudo mdutil -i on /Volumes/$NAME
}
